#!/usr/bin/env ruby

require 'net/http'
require 'json'
require 'fileutils'

HEADERS_RAW = IO.readlines(ARGV[0]).map(&:strip)
HOST = HEADERS_RAW
       .find { |line| line.start_with? "Host:" }
       .sub(/Host: /, '')
HEADERS_PARSED = HEADERS_RAW
                 .grep(/[A-Za-z-]+:/)
                 .reject { |line| line.start_with? "Host:" }
                 .map { |line| line.split(/:\s*/, 2) }
                 .to_h

PATHS = IO.readlines(ARGV[1]).map(&:strip)

TARGET = ARGV[2]
FileUtils.mkdir_p TARGET
PATHS.each do |path|
  uri = URI("http://#{HOST}#{path}")
  req = Net::HTTP::Get.new(uri)

  HEADERS_PARSED.each do |key, value|
    req[key] = value
  end

  Net::HTTP.start(uri.host, uri.port) do |http|
    res = http.request req
    filename = path.sub(/^\//, '').tr('/', '-')
    File.write("#{TARGET}/#{filename}", JSON.pretty_generate(JSON.parse(res.body)))
  end
end
