#!/usr/bin/env ruby

require 'net/http'

HEADERS_RAW = IO.readlines(ARGV[0]).map(&:strip)
HOST = HEADERS_RAW
       .find { |line| line.start_with? "Host:" }
       .sub(/Host: /, '')
HEADERS_PARSED = HEADERS_RAW
                 .grep(/[A-Za-z-]+:/)
                 .reject { |line| line.start_with? "Host:" }
                 .map { |line| line.split(/:\s*/, 2) }
                 .to_h

PATHS = IO.readlines(ARGV[1]).map(&:strip)

TARGET = ARGV[2]
File.open(TARGET, 'w') do |f|
  PATHS.each do |path|
    uri = URI("http://#{HOST}#{path}")
    req = Net::HTTP::Get.new(uri)

    HEADERS_PARSED.each do |key, value|
      req[key] = value
    end

    Net::HTTP.start(uri.host, uri.port) do |http|
      res = http.request req
      filename = path.sub(/^\//, '').tr('/', '-')
      f.puts "####{filename}###"
      f.puts "#{res.body}\n"
    end
  end
end
