#!/usr/bin/env ruby

require 'net/http'

def parse_options(header_file, path_file)
  raw = IO.readlines(header_file).map(&:strip)
  headers = raw
            .grep(/[A-Za-z-]+:/)
            .reject { |line| line.start_with? "Host:" }
            .map { |line| line.split(/:\s*/, 2) }
            .to_h

  {
    headers: headers,
    paths: IO.readlines(path_file).map(&:strip),
    host: headers['Host']
  }
end

def amble(headers:, paths:, host:)
  paths.each do |path|
    uri = URI("http://#{host}#{path}")
    req = Net::HTTP::Get.new(uri)

    headers.each do |key, value|
      req[key] = value
    end

    Net::HTTP.start(uri.host, uri.port) do |http|
      res = http.request req
      filename = path.sub(/^\//, '').tr('/', '-')
      puts "####{filename}###"
      puts "#{res.body}\n"
    end
  end
end

if $PROGRAM_NAME == __FILE__
  opts = parse_options(ARGV[0], ARGV[1])
  amble(opts)
end
